version: '3'
services:
  doom:
    image: elliottking/doom-wasm:0.1.1
    container_name: doom
    expose:
      - "8000"  # Expose to network, no host mapping needed
    restart: unless-stopped
    networks:
      - services
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"   # Add for HTTP redirect
      - "443:443"
    volumes:
      - /nginx/custom.conf:/etc/nginx/nginx.conf:ro  # Replace default config
      - /nginx/server.crt:/etc/nginx/server.crt:ro
      - /nginx/server.key:/etc/nginx/server.key:ro
    restart: always
    networks:
      services:
        ipv4_address: 172.20.0.4
networks:
  services:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24